### ISSUE TITLE
docker network 理解 

### ISSUE THREAD

**Issue by hirosi1900day** [hirosi1900day/skill-up#45]
```
docker network create --driver bridge --subnet=172.30.0.0/16 sample_graph_network

```
上記をやった後に
```
version: '3.8'
services:
  nginx:
    image: nginx:1.17.3-alpine
    container_name: nginx
    ports:
      - "3443:3443"
      - "8443:8443"
    volumes:
      - ".docker/nginx/conf.d:/etc/nginx/conf.d"
      - ".docker/nginx/cert/localhost.pem:/etc/certs/localhost.pem"
      - ".docker/nginx/cert/localhost-key.pem:/etc/certs/localhost-key.pem"
    networks:
      sample_graph_network:
        ipv4_address: 172.30.0.11

  front:
    container_name: front
    build:
      context: .
      target: dev
      dockerfile: .docker/front/Dockerfile
    tty: true
    volumes:
      - ./src/:/app
    environment:
    # ホットリロード対応
     - WATCHPACK_POLLING=true
    ports:
    - "3000:3000"
    networks:
      sample_graph_network:
        ipv4_address: 172.30.0.10

networks:
  sample_graph_network:
    external: true
```

**Comment by hirosi1900day** [comment]
https://qiita.com/WebEngrChild/items/d4bc23bf352e7aa46361

**Comment by hirosi1900day** [comment]
test4/docker-compose.yml
```
version: '3.8'
services:
  nginx:
    image: nginx:1.17.3-alpine
    ports:
      - "85:80"
```
上記でtest4_default というdocker networkが自動で作成される

test4_defaultというdocker-composeによりデフォルトで作成されたネットワークに別のdocker-composeのコンテナを所属させるには以下のようにする

test5/docker-compose.yml
```
version: '3.8'
services:
  nginx:
    image: nginx:1.17.3-alpine
    ports:
      - "86:80"
    networks:
      - test4_default
networks:
  test4_default:
    external: true
```

確認

```sh
docker network inspect test4_default
```

結果
```
 % docker network inspect test4_default
[
    {
        "Name": "test4_default",
        "Id": "e3438a002cdedd2e3994f393a623c4c1e07a346cc3c57284c1071a68535ce00d",
        "Created": "2024-02-14T13:10:40.011968343Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.29.0.0/16",
                    "Gateway": "172.29.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "59f1b1e2704069c7d857a7c9efa22dcb82adf0b8298fde0f0364d3fc4bb3d359": {
                "Name": "test5-nginx-1",
                "EndpointID": "8be273a3d1c3e666a3004c0349bac09b2fce936358777b70ccfa9169032b30cf",
                "MacAddress": "02:42:ac:1d:00:03",
                "IPv4Address": "172.29.0.3/16",
                "IPv6Address": ""
            },
            "7dd533f0a3d138dd588f92fb97b7785e9dd5eea5ffe916e2f96dc56476e548e1": {
                "Name": "test4-nginx-1",
                "EndpointID": "de2338709b6290f482ec8d67a4ce3dd31ada527e8310997a79b1aad8f020b468",
                "MacAddress": "02:42:ac:1d:00:02",
                "IPv4Address": "172.29.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "test4",
            "com.docker.compose.version": "2.23.0"
        }
    }
]
```

ちなみにdocker-composeが自動的に作成するネットワーク名は
ディレクトリー名_defualtになる
