### ISSUE TITLE
terraform-docsからドキュメント生成

### ISSUE THREAD

**Issue by hirosi1900day** [hirosi1900day/skill-up#61]

**Comment by hirosi1900day** [comment]
```yml
name: Generate terraform docs
on: [pull_request]

jobs:
  doc:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push changes back to modules
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
```
